version: '3.8'

services:

  app_final:
    build:
      dockerfile: build/Dockerfile.app
    ports:
      - "8000:5000"
    env_file:
      - ./env.dev.app
    depends_on:
      psql_projeto_final:
        condition: service_healthy
    volumes:
      - ./src:/app
    networks:
      - network_final

  psql_projeto_final:
    image: postgres:15
    ports:
      - '5432:5432'
    expose:
      - '5432'
    env_file: 
      - ./env.dev.psql
    volumes:
      - ./psql_start:/docker-entrypoint-initdb.d
    networks:
      - network_final
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  network_final: